Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.define "ansible" do |ansible|
    ansible.vm.provision "file", source: "~/Documents/Learning/Vagrant/files/sshd_config", destination: "/tmp/sshd_config"
    ansible.vm.provision "file", source: "~/Documents/Learning/Vagrant/files/ssh", destination: "/tmp/ssh"
    ansible.vm.provision "shell", path: "~/Documents/Learning/Vagrant/scripts/ansible.sh"
    ansible.vm.hostname == "ansible.example.com"
    ansible.vm.network "private_network", ip: "192.168.111.2"
  end  
  
  config.vm.define "agent" do |agent|
    agent.vm.provision "file", source:
    "~/Documents/Learning/Vagrant/files/sshd_config", destination: "/tmp/sshd_config"
    agent.vm.provision "shell", path: "~/Documents/Learning/Vagrant/scripts/agent.sh"
    agent.vm.hostname == "agent.example.com"
    agent.vm.network "private_network", ip: "192.168.111.3"
  end

end


