Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.define "ansible" do |ansible|
    ansible.vm.provision "shell", path: ../scripts/ansible.
    ansible.vm.hostname == "ansible.example.com"
    ansible.vm.network "private_network", ip: "192.168.111.2"
  end  
  
  config.vm.define "ansible" do |agent|
    agent.vm.provision "shell", path: ../scripts/agent.sh
    agent.vm.hostname == "agent.example.com"
    agent.vm.network "private_network", ip: "192.168.111.3"
  end

end
